import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { useRouter } from "next/router";
import Link from "next/link";

export default function Home() {
  const router = useRouter();

  function handleClick() {
    router.push("/product");
    // router.replace("/product");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/users">
          <a>Users</a>
        </Link>
        <button onClick={handleClick}>Place Order</button>
      </main>
    </div>
  );
}
